# Generated by Django 3.1.2 on 2020-10-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=40)),
                ('text', models.TextField()),
                ('typingData', models.TextField()),
                ('dateOfData', models.DateTimeField()),
            ],
        ),
    ]
